#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      -  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDh5j6DLdE66Ohm4fnZB5mjAA9/7K6HlTTgU8oaJe4kyBspL3d5SDy6y/grgXPAYkpNfKG2ULO8rW/4oRPFjITuLD5YM8AKZub6908UuOT1XZZAv1PtBsAzmyxR8phgshROetXojxH+hgsb1mGjKnfUjbPHkq8Z9mgaW2J4uCe2lRIpXOubqjq/9TsOQIdoqObVTF20B/mE5LXOSK8y4br3q7J4pmthYEemaAAhktpLBkq8eZgAh2efCDuVEj6vjTZQwCe+7+HHBF6XBeBHIKyF25dCHZNmIknggl65agQtr9qcRwoi7ePrJS18ABhnfCWBIVmMan5QHFaeXZTDWp0RJA9zojIYGtju4l32zzOFquYBaizg6STc8ey+fsTtTvZXq6bJqWSkRaWnPX8v/swP4doRObFZrwXMNV1M08zSP3NM+tAxdfRzQZINyZmvf1ZBpHzsLSz/eOsWouMWsYAoCSBR8xT0znClmc4GXru1LfjFtTMIDUaFexgSgvdh4ZE= tom@example.com
apt:
  primary:
    - arches: [default]
      search_dns: True

# Downloads the Python package
packages:
  - python

# Launch the SimpleHTTPServer on port 80
runcmd:
  - python -m SimpleHTTPServer 80 &

final_message: "The system is finally up, after $UPTIME seconds"