#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - lab

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: lab
    gecos: lab
    primary_group: lab
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    plain_text_passwd: 'lab123'
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0vvLjt1MUK4emeYSdHDkShA4ji+fch6ruX6zSLxPx0YMyPGQZ7CLFbLpBqOh4Aqo38V8lo0h0vnzRAs2Kpr6jfwTVyAsFFMm0LRsQbO9nSA3cY7RT/t4a7ms6Eq52wnzvjeKHM6lR0tqi0dL5u/uK54dnTE/urLYzl2s5Ue9uOBCXAJVb5UH9+htCApNQBon7NGR3SrcxnGwuy6RHnwgE6O83pNryaARX4gFXEeVWTyClcJGlTWXrU7gnkIgYZfH9VFr7KJ9n4n9iDS6kV+jAVMu574tpqOvUwqp32bw83jrqQA68xnFWSjDrXHZ3PH6Nidze+Uc0zUDJ7YUDXoPtD0zf0LpKO+78xudFtMsgKOcFEG/53z1LRA69NXXhMbUCDjuDETtZvudiM/rvZAWfiQq7eNNeBSSwAYRLzovjVtmoblZku9SBHTZobm5R3lgQXEC5WOyTKXQzhP2uBxZtGTnoQuVSWCM93tTwBZ/UXbZqD03k8NeflBJfZ4KIT2E= lab@example.com

write_files:
  - path: /index.html
    content: |
      <html>
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;700&display=swap" rel="stylesheet">
      <head>
        <title>Test Website</title>
      </head>
      <body>
        <br/><br/>
        <h1 align="center" style="font-family:Ubuntu">WELCOME TO YOUR TEST WEBSITE</h1>
        <br/>
        <h3 align="center" style="font-family:Ubuntu">This is all about AWS flow logs </h3>
        <br/><br/>
        <p align="center">
          <img src="https://d2908q01vomqb2.cloudfront.net/da4b9237bacccdf19c0760cab7aec4a8359010b0/2019/09/13/2019-08-13_10-41-04.png">
        </p>
        <br/>
      </body>
      </html>

apt:
  primary:
    - arches: [default]
      search_dns: True

# Downloads the Python package
packages:
  - python

# Launch the SimpleHTTPServer on port 80
runcmd:
  - python -m SimpleHTTPServer 80 &

final_message: "The system is finally up, after $UPTIME seconds"