#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - lab

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: lab
    gecos: lab
    primary_group: lab
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/lab
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      ssh-rsa <YOUR-PUBLIC-KEY-HERE>

write_files:
  - path: /home/lab/key.pub
    content: |
      ssh-rsa <YOUR-PUBLIC-KEY-HERE>
  - path: /home/lab/key
    content: |
      <YOUR-PRIVATE-KEY-HERE>

apt:
  primary:
    - arches: [default]
      search_dns: True

# Downloads the Traceroute package
packages:
  - traceroute

# Checking ping & traceroute to google.com
runcmd:
  - ping -c1 google.com >> ec2.log
  - traceroute google.com >> ec2.log

final_message: "The system is finally up, after $UPTIME seconds"
